 version: '2'
 services:
   db:
     image: postgres
   node:
     build: "react/"
     entrypoint: sh entrypoint.sh
     working_dir: /home/node
     ports:
       - 8101:3000
     volumes:
       - ./react:/home/node
   django:
     build: "django/"
     command: python manage.py runserver 0.0.0.0:8000
     volumes:
       - ./django:/code
     ports:
       - "${PORT}:8000"
     depends_on:
       - node
       - db
